// users
export const GET_USERS_LOADING = 'GET_USERS_LOADING';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';
export const DISMISS_USERS_LIST = 'DISMISS_USERS_LIST';
export const GET_SINGLE_USER_LOADING = 'GET_SINGLE_USER_LOADING';
export const GET_SINGLE_USER_SUCCESS = 'GET_SINGLE_USER_SUCCESS';
export const GET_SINGLE_USER_FAIL = 'GET_SINGLE_USER_FAIL';
export const DISMMISS_USER = 'DISMMISS_USER';
