export const users = [
  {
    login: 've',
    id: 22438697,
    node_id: 'MDQ6VXNlcjIyNDM4Njk3',
    avatar_url: 'https://avatars.githubusercontent.com/u/22438697?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/ve',
    html_url: 'https://github.com/ve',
    followers_url: 'https://api.github.com/users/ve/followers',
    following_url: 'https://api.github.com/users/ve/following{/other_user}',
    gists_url: 'https://api.github.com/users/ve/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/ve/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/ve/subscriptions',
    organizations_url: 'https://api.github.com/users/ve/orgs',
    repos_url: 'https://api.github.com/users/ve/repos',
    events_url: 'https://api.github.com/users/ve/events{/privacy}',
    received_events_url: 'https://api.github.com/users/ve/received_events',
    type: 'User',
    site_admin: false,
    score: 1.0
  },
  {
    login: 'bouquetrender',
    id: 16361069,
    node_id: 'MDQ6VXNlcjE2MzYxMDY5',
    avatar_url: 'https://avatars.githubusercontent.com/u/16361069?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/bouquetrender',
    html_url: 'https://github.com/bouquetrender',
    followers_url: 'https://api.github.com/users/bouquetrender/followers',
    following_url:
      'https://api.github.com/users/bouquetrender/following{/other_user}',
    gists_url: 'https://api.github.com/users/bouquetrender/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/bouquetrender/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/bouquetrender/subscriptions',
    organizations_url: 'https://api.github.com/users/bouquetrender/orgs',
    repos_url: 'https://api.github.com/users/bouquetrender/repos',
    events_url: 'https://api.github.com/users/bouquetrender/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/bouquetrender/received_events',
    type: 'User',
    site_admin: false,
    score: 1.0
  },
  {
    login: 'vercel',
    id: 14985020,
    node_id: 'MDEyOk9yZ2FuaXphdGlvbjE0OTg1MDIw',
    avatar_url: 'https://avatars.githubusercontent.com/u/14985020?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/vercel',
    html_url: 'https://github.com/vercel',
    followers_url: 'https://api.github.com/users/vercel/followers',
    following_url: 'https://api.github.com/users/vercel/following{/other_user}',
    gists_url: 'https://api.github.com/users/vercel/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/vercel/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/vercel/subscriptions',
    organizations_url: 'https://api.github.com/users/vercel/orgs',
    repos_url: 'https://api.github.com/users/vercel/repos',
    events_url: 'https://api.github.com/users/vercel/events{/privacy}',
    received_events_url: 'https://api.github.com/users/vercel/received_events',
    type: 'Organization',
    site_admin: false,
    score: 1.0
  },
  {
    login: 'vedovelli',
    id: 151001,
    node_id: 'MDQ6VXNlcjE1MTAwMQ==',
    avatar_url: 'https://avatars.githubusercontent.com/u/151001?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/vedovelli',
    html_url: 'https://github.com/vedovelli',
    followers_url: 'https://api.github.com/users/vedovelli/followers',
    following_url:
      'https://api.github.com/users/vedovelli/following{/other_user}',
    gists_url: 'https://api.github.com/users/vedovelli/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/vedovelli/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/vedovelli/subscriptions',
    organizations_url: 'https://api.github.com/users/vedovelli/orgs',
    repos_url: 'https://api.github.com/users/vedovelli/repos',
    events_url: 'https://api.github.com/users/vedovelli/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/vedovelli/received_events',
    type: 'User',
    site_admin: false,
    score: 1.0
  },
  {
    login: 'zhilepeng',
    id: 32957641,
    node_id: 'MDQ6VXNlcjMyOTU3NjQx',
    avatar_url: 'https://avatars.githubusercontent.com/u/32957641?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/zhilepeng',
    html_url: 'https://github.com/zhilepeng',
    followers_url: 'https://api.github.com/users/zhilepeng/followers',
    following_url:
      'https://api.github.com/users/zhilepeng/following{/other_user}',
    gists_url: 'https://api.github.com/users/zhilepeng/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/zhilepeng/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/zhilepeng/subscriptions',
    organizations_url: 'https://api.github.com/users/zhilepeng/orgs',
    repos_url: 'https://api.github.com/users/zhilepeng/repos',
    events_url: 'https://api.github.com/users/zhilepeng/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/zhilepeng/received_events',
    type: 'User',
    site_admin: false,
    score: 1.0
  },
  {
    login: 'velopert',
    id: 17202261,
    node_id: 'MDQ6VXNlcjE3MjAyMjYx',
    avatar_url: 'https://avatars.githubusercontent.com/u/17202261?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/velopert',
    html_url: 'https://github.com/velopert',
    followers_url: 'https://api.github.com/users/velopert/followers',
    following_url:
      'https://api.github.com/users/velopert/following{/other_user}',
    gists_url: 'https://api.github.com/users/velopert/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/velopert/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/velopert/subscriptions',
    organizations_url: 'https://api.github.com/users/velopert/orgs',
    repos_url: 'https://api.github.com/users/velopert/repos',
    events_url: 'https://api.github.com/users/velopert/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/velopert/received_events',
    type: 'User',
    site_admin: false,
    score: 1.0
  }
];

export const user = {
  login: 'uu',
  id: 95994,
  node_id: 'MDQ6VXNlcjk1OTk0',
  avatar_url: 'https://avatars.githubusercontent.com/u/95994?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/uu',
  html_url: 'https://github.com/uu',
  followers_url: 'https://api.github.com/users/uu/followers',
  following_url: 'https://api.github.com/users/uu/following{/other_user}',
  gists_url: 'https://api.github.com/users/uu/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/uu/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/uu/subscriptions',
  organizations_url: 'https://api.github.com/users/uu/orgs',
  repos_url: 'https://api.github.com/users/uu/repos',
  events_url: 'https://api.github.com/users/uu/events{/privacy}',
  received_events_url: 'https://api.github.com/users/uu/received_events',
  type: 'User',
  site_admin: false,
  name: 'Michael Pirogov',
  company: null,
  blog: '',
  location: 'Montenegro, Budva',
  email: null,
  hireable: true,
  bio: 'Cirque Do Sopley',
  twitter_username: null,
  public_repos: 51,
  public_gists: 1,
  followers: 20,
  following: 25,
  created_at: '2009-06-16T16:56:11Z',
  updated_at: '2023-06-14T09:51:23Z'
};
